# Generated by Django 4.2.1 on 2023-05-20 07:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cotent_upload',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
